# Generated by Django 5.0.6 on 2024-10-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_student_delete_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='FormData',
        ),
    ]
